spring.application.name=TicketManagerCatalogAPI
spring.mongodb.representation.uuid=standard
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
eureka.client.service-url.defaultZone=http://EurekaRegistry:8761/eureka/