services:
  catalog:
    build:
      context: ./catalog
    container_name: CatalogAPI
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://catalogMongoDB:27017/ticketmanager
    depends_on:
      - catalogMongoDB
    networks:
      - ticket-manager-network

  catalogMongoDB:
    image: mongo:latest
    container_name: CatalogMongoDB
    ports:
      - 27017:27017
    volumes:
      - ./MongoDB/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./MongoDB/data:/docker-entrypoint-initdb.d/seed-data:ro
    networks:
      - ticket-manager-network

networks:
  ticket-manager-network:
    driver: bridge