services:
  catalog:
    build:
      context: ./catalog
    container_name: CatalogAPI
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://catalogMongoDB:27017/ticketmanager
    depends_on:
      - catalogMongoDB
    networks:
      - ticket-manager-network

  catalogMongoDB:
    image: mongo:latest
    container_name: CatalogMongoDB
    ports:
      - 27017:27017
    volumes:
      - ./MongoDB/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./MongoDB/data:/docker-entrypoint-initdb.d/seed-data:ro
    networks:
      - ticket-manager-network
  
  basket:
    build:
      context: ./basket
    container_name: BasketServiceAPI
    ports:
      - "8082:8082"
    environment:
      - JWT_KEY=2YgFrs$3Z8k@bq!R7u%4Lm#N6y^P0t&W2YgFrs$3Z8k@bq!R7u%4Lm#N6y^P0t&W
    depends_on:
      - basketRedisDB
      - rabbitMQ
    networks:
      - ticket-manager-network

  basketRedisDB:
    image: redis:latest
    container_name: BasketRedisDB
    ports:
      - 6379:6379
    networks:
      - ticket-manager-network

  user:
    build:
      context: ./UserService
    container_name: UserServiceAPI
    ports: 
      - "8085:8080"
    depends_on:
      - userSQLDB
    networks:
      - ticket-manager-network
    # restart: "on-failure"

  userSQLDB:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: UserSQLDB
    ports:
      - 1434:1433
    environment:
      - SA_PASSWORD=dev123!!
      - MSSQL_DATABASE=UserServiceDB
      - ACCEPT_EULA=Y
    volumes:
      - userservicevolume:/var/opt/mssql
      - ./SQL/DBSetup.sql:/docker-entrypoint-initdb.d/DBSetup.sql:ro
    networks:
      - ticket-manager-network
  
  auth:
    build:
      context: ./AuthService
    container_name: AuthServiceAPI
    ports: 
      - "8084:8080"
    depends_on:
      - user
    networks:
      - ticket-manager-network

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=dev123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ticket-manager-network
  
  messageservice:
    build:
      context: ./MessageService
    container_name: MessageService
    depends_on:
      rabbitMQ:
        condition: service_healthy
    networks:
      - ticket-manager-network
    restart: on-failure
  
  orders:
    build:
      context: ./OrderService
    container_name: OrderServiceAPI
    ports: 
      - "8083:8080"
    depends_on:
      - user
      - catalog
      - ordersSQLDB
      - rabbitMQ
    networks:
      - ticket-manager-network

  ordersSQLDB:
    image: mysql:latest
    container_name: OrdersSQLDB
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev123
      - MYSQL_DATABASE=OrdersDB
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ticket-manager-network

  eureka:
    image: steeltoeoss/eureka-server:latest
    container_name: EurekaRegistry
    ports:
      - 8761:8761
    networks:
      - ticket-manager-network


networks:
  ticket-manager-network:
    driver: bridge

volumes:
  userservicevolume:
  rabbitmq_data:
  db-data: