// This file is generated by VSCode's Copilot to autopopulate the MongoDB with some set data

// MongoDB initialization script for ticketmanager
// Using in-script seed docs (cat() is unavailable in some Mongo shell environments)
(function () {
    const dbName = 'ticketmanager';
    const collName = 'tickets';

    const docs = [
        {
            _id: 'b0d8a7f4-a123-4c1f-b2ad-cf78867f9c52',
            event: 'Spring Fest Concert',
            price: 59.99,
            description: 'Outdoor live concert featuring local bands.',
            eventDate: '2026-05-15T00:00:00Z'
        },
        {
            _id: 'a5c9d4e2-1100-4480-ba87-6f2b3bb6d8c3',
            event: 'Cinema Night Premiere',
            price: 12.5,
            description: 'Premiere screening with free popcorn.',
            eventDate: '2026-06-10T00:00:00Z'
        },
        {
            _id: 'c3fa8dcd-237d-4edb-9d5f-760a2f7da1a9',
            event: 'Tech Talk Meetup',
            price: 0.0,
            description: 'Community meetup and networking event.',
            eventDate: '2026-07-08T00:00:00Z'
        }
    ];

    const targetDb = db.getSiblingDB(dbName);

    if (targetDb.getCollection(collName).countDocuments() > 0) {
        print('Skipping seed import; collection ' + collName + ' already has data.');
        return;
    }

    docs.forEach(doc => {
        doc._id = UUID(doc._id);
        doc.eventDate = ISODate(doc.eventDate);
    });

    const result = targetDb.getCollection(collName).insertMany(docs);
    print('Inserted ' + result.insertedCount + ' documents into ' + dbName + '.' + collName);
})();
