FROM python:3.13-slim


WORKDIR /app

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV REDIS_HOST=BasketRedisDB
ENV REDIS_PORT=6379
ENV TICKET_SERVICE_URL=http://CatalogAPI:8080/api/tickets

ENV EUREKA_SERVER=http://EurekaRegistry:8761/eureka/
ENV ENABLE_EUREKA=true
ENV SERVICE_NAME=BasketServiceAPI
ENV BASKET_SERVICE_IP=BasketServiceAPI
ENV BASKET_SERVICE_PORT=8082

EXPOSE 8082

CMD ["uvicorn", "basket_rest_controller:app", "--host", "0.0.0.0", "--port", "8082"]